import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    mySkills: 'My Skills',
    houseBuilding: 'House/building improvement',
    messages: 'Messages',
    Mechanic: 'Mechanic',
    Transportation: 'Transportation',
    TechnologyHardware: 'Technology Hardware',
    whatAreYouGoodAt: 'What are you good at?',
    save: 'Save',
    termsofSerivice: 'terms of service',
    BySaving: 'By saving, you agree to our skills',
    itemsSelected: v => `${v} Items Selected`,
    help: 'Help',
    settings: 'Settings',
    account: 'Account',
    notifications: 'Notifications',
    verified: 'Verified',
    unverified: 'Unverified',
    verify: 'Verify',
    weSendAcode: num => `We sent a code to ${num}`,
    resendCode: 'Resend Code',
    next: 'Next',
    continue: 'Continue',
    Acceptedtoajob: 'Accepted to a job',
    Deniedtoajob: 'Denied to a job',
    Receiveastarrating: 'Receive a star rating',
    Newjobsinyourarea: 'New jobs in your area',
    Jobiscancelled: 'Job is cancelled',
    byDeleting: 'By deleting your account you will:',
    deletingAllInfo: '- Delete all information and profile details',
    deletingAllHistory: '- Delete all job history ',
    deletingAllOpp: '- Delete potential opportunities',
    deleteAccount: 'Delete Account',
    phoneNumber: 'Phone Number',
    email: 'Email',
    pin: 'Pin',
    unpin: 'Unpin',
    delete: 'Delete',
    unhide: 'Unhide',
    hide: 'Hide',
    reply: 'Reply',
    copy: 'Copy',
    edit: 'Edit',
    forward: 'Forward',
  },
});

export default strings;
